kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
  # 空串表示使用core API Group
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]